/**
 * CareSync Initial Realistic Seed Dataset
 *
 * Fully interconnected healthcare ecosystem featuring:
 * - Patient: Rahul Sharma (CS-2048-7392)
 * - Doctors: Dr. Rahul Mehta (GP, Verified), Dr. Ananya Sharma (Cardiologist, Verified), Dr. Kavya Menon (Endocrinologist, Verified)
 * - Laboratory: ABC Diagnostics (Verified)
 * - Pharmacy: XYZ Pharmacy (Verified)
 * - Caregiver: Priya Sharma
 * - Admin: CareSync Compliance Admin
 * - Linked Consultations, Prescriptions, Lab Reports, Pharmacy Orders, Consent, Vitals, and Journey Events.
 */

export const seedUsers = [
  {
    id: 1,
    email: "rahul.sharma@example.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncPatient2026",
    role: "PATIENT",
    fullName: "Rahul Sharma",
    phone: "+91 98765 43210",
    avatarUrl: null,
  },
  {
    id: 2,
    email: "dr.rahul.mehta@northstarmed.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncDoctorGP2026",
    role: "DOCTOR",
    fullName: "Dr. Rahul Mehta",
    phone: "+91 98765 11223",
    avatarUrl: null,
  },
  {
    id: 3,
    email: "dr.ananya.sharma@astergrove.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncDoctorCardio2026",
    role: "DOCTOR",
    fullName: "Dr. Ananya Sharma",
    phone: "+91 98765 33445",
    avatarUrl: null,
  },
  {
    id: 4,
    email: "dr.kavya.menon@wellspring.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncDoctorEndo2026",
    role: "DOCTOR",
    fullName: "Dr. Kavya Menon",
    phone: "+91 98765 55667",
    avatarUrl: null,
  },
  {
    id: 5,
    email: "lab.tech@abcdiagnostics.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncLab2026",
    role: "LAB_STAFF",
    fullName: "Suresh Nair",
    phone: "+91 98765 77889",
    avatarUrl: null,
  },
  {
    id: 6,
    email: "pharmacy@xyzpharmacy.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncPharm2026",
    role: "PHARMACY_STAFF",
    fullName: "Vikram Sethi",
    phone: "+91 98765 99001",
    avatarUrl: null,
  },
  {
    id: 7,
    email: "priya.sharma@example.com",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncCaregiver2026",
    role: "CAREGIVER",
    fullName: "Priya Sharma",
    phone: "+91 98765 88221",
    avatarUrl: null,
  },
  {
    id: 8,
    email: "admin@caresync.internal",
    passwordHash: "$2a$10$demoHashedPasswordCareSyncAdmin2026",
    role: "ADMIN",
    fullName: "CareSync Administrator",
    phone: "+91 98765 00000",
    avatarUrl: null,
  },
];

export const seedPatients = [
  {
    id: 1,
    userId: 1,
    careSyncId: "CS-2048-7392",
    dateOfBirth: "1992-04-12",
    gender: "Male",
    bloodGroup: "B+",
    emergencyContactName: "Priya Sharma",
    emergencyContactPhone: "+91 98765 88221",
    emergencyContactRelation: "Spouse",
    idStatus: "VERIFIED",
    address: "Flat 402, Palm Meadows, Indiranagar, Bengaluru, Karnataka 560038",
    allergies: ["Penicillin"],
    chronicConditions: ["Borderline Hypertension", "Pre-diabetes"],
  },
];

export const seedDoctors = [
  {
    id: 1,
    userId: 2,
    fullName: "Dr. Rahul Mehta",
    specialization: "General Physician",
    qualification: "MBBS, MD (Internal Medicine)",
    licenseNumber: "KMC-2012-84729",
    experienceYears: 14,
    organization: "Northstar Medical Centre",
    location: "Indiranagar, Bengaluru",
    fee: 850,
    rating: "4.90",
    verificationStatus: "VERIFIED",
    verificationDocuments: [
      { name: "Medical Registration Certificate.pdf", verified: true, verifiedAt: "2026-01-10" },
      { name: "MD Qualification Degree.pdf", verified: true, verifiedAt: "2026-01-10" }
    ],
    nextSlot: "Today, 4:30 PM",
    initials: "RM",
    bio: "Consultant Physician with 14 years of clinical experience in preventative internal medicine, cardiometabolic disease, and longitudinal adult care.",
  },
  {
    id: 2,
    userId: 3,
    fullName: "Dr. Ananya Sharma",
    specialization: "Cardiologist",
    qualification: "MBBS, MD, DM (Cardiology), FACC",
    licenseNumber: "KMC-2008-39201",
    experienceYears: 18,
    organization: "Aster Grove Heart Clinic",
    location: "Koramangala, Bengaluru",
    fee: 1200,
    rating: "4.95",
    verificationStatus: "VERIFIED",
    verificationDocuments: [
      { name: "DM Cardiology Council License.pdf", verified: true, verifiedAt: "2026-01-08" },
      { name: "FACC Fellowship Certificate.pdf", verified: true, verifiedAt: "2026-01-08" }
    ],
    nextSlot: "Tomorrow, 10:00 AM",
    initials: "AS",
    bio: "Senior Interventional Cardiologist specializing in preventive cardiovascular diagnostics, hypertension management, and lipidology.",
  },
  {
    id: 3,
    userId: 4,
    fullName: "Dr. Kavya Menon",
    specialization: "Endocrinology",
    qualification: "MBBS, MD, DNB (Endocrinology)",
    licenseNumber: "KMC-2015-62019",
    experienceYears: 10,
    organization: "WellSpring Specialty Care",
    location: "HSR Layout, Bengaluru",
    fee: 950,
    rating: "4.85",
    verificationStatus: "VERIFIED",
    verificationDocuments: [
      { name: "DNB Endocrinology Registration.pdf", verified: true, verifiedAt: "2026-01-15" }
    ],
    nextSlot: "Friday, 2:15 PM",
    initials: "KM",
    bio: "Specialist in metabolic health, glycemic variability management, thyroid disorders, and lifestyle intervention protocols.",
  },
];

export const seedOrganizations = [
  {
    id: 1,
    name: "ABC Diagnostics",
    orgType: "LABORATORY",
    licenseNumber: "NABL-LAB-2024-918",
    address: "44/2 Richmond Road, Shanthala Nagar, Bengaluru, Karnataka 560025",
    branches: ["Richmond Road Central", "Indiranagar Collection Centre", "Whitefield Hub"],
    contactPhone: "+91 80 4123 9000",
    contactEmail: "reports@abcdiagnostics.com",
    operatingHours: "Mon-Sat: 07:00 AM - 09:00 PM, Sun: 07:00 AM - 02:00 PM",
    verificationStatus: "VERIFIED",
  },
  {
    id: 2,
    name: "XYZ Pharmacy",
    orgType: "PHARMACY",
    licenseNumber: "KA-DRUG-2024-541",
    address: "12, 100ft Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038",
    branches: ["Indiranagar Main", "Koramangala 4th Block", "HSR Sector 2"],
    contactPhone: "+91 80 2520 1199",
    contactEmail: "orders@xyzpharmacy.com",
    operatingHours: "24x7 Dispensing & Home Delivery",
    verificationStatus: "VERIFIED",
  },
];

export const seedOrganizationMembers = [
  {
    id: 1,
    organizationId: 1,
    userId: 5,
    memberRole: "TECHNICIAN",
  },
  {
    id: 2,
    organizationId: 2,
    userId: 6,
    memberRole: "PHARMACIST",
  },
];

export const seedCaregivers = [
  {
    id: 1,
    patientId: 1,
    caregiverUserId: 7,
    relationship: "Spouse",
    permissions: ["APPOINTMENTS", "TASKS", "FOLLOW_UPS", "MEDICATIONS", "JOURNEY_PROGRESS", "NOTIFICATIONS"],
    status: "ACTIVE",
  },
];

export const seedDoctorAvailability = [
  {
    id: 1,
    doctorId: 1,
    dayOfWeek: 1, // Monday
    startTime: "09:00",
    endTime: "18:00",
    slotDurationMinutes: 30,
    breakStartTime: "13:00",
    breakEndTime: "14:00",
    mode: "BOTH",
    isActive: true,
  },
  {
    id: 2,
    doctorId: 1,
    dayOfWeek: 2, // Tuesday
    startTime: "09:00",
    endTime: "18:00",
    slotDurationMinutes: 30,
    breakStartTime: "13:00",
    breakEndTime: "14:00",
    mode: "BOTH",
    isActive: true,
  },
  {
    id: 3,
    doctorId: 2, // Dr. Ananya Sharma
    dayOfWeek: 2,
    startTime: "10:00",
    endTime: "17:00",
    slotDurationMinutes: 45,
    breakStartTime: "13:30",
    breakEndTime: "14:30",
    mode: "BOTH",
    isActive: true,
  },
];

export const seedAppointments = [
  {
    id: 1,
    patientId: 1,
    doctorId: 1, // Dr. Rahul Mehta
    bookedByDoctorId: null,
    appointmentType: "PATIENT_TO_DOCTOR",
    date: "2026-08-12",
    time: "10:00 AM",
    mode: "In-clinic visit",
    status: "COMPLETED",
    fee: 850,
    reason: "Initial evaluation for occasional exertional fatigue and mild dizziness",
    notes: "Patient attended on time. Advised baseline blood investigations and lifestyle review.",
  },
  {
    id: 2,
    patientId: 1,
    doctorId: 1, // Dr. Rahul Mehta
    bookedByDoctorId: null,
    appointmentType: "PATIENT_TO_DOCTOR",
    date: "2026-08-28",
    time: "04:30 PM",
    mode: "Video consultation",
    status: "CONFIRMED",
    fee: 850,
    reason: "Follow-up consultation to review comprehensive metabolic & lipid panel results",
    notes: "Scheduled video consultation to discuss HbA1c, lipid management, and specialist referral.",
  },
  {
    id: 3,
    patientId: 1,
    doctorId: 2, // Dr. Ananya Sharma (Cardiologist)
    bookedByDoctorId: 1, // Booked/referred by Dr. Rahul Mehta
    appointmentType: "DOCTOR_TO_DOCTOR",
    date: "2026-09-02",
    time: "11:00 AM",
    mode: "In-clinic visit",
    status: "CONFIRMED",
    fee: 1200,
    reason: "Cardiology specialist evaluation for elevated non-HDL cholesterol and family risk profile",
    notes: "Doctor-to-Doctor referral appointment arranged by Dr. Rahul Mehta.",
  },
];

export const seedConsultations = [
  {
    id: 1,
    appointmentId: 1,
    patientId: 1,
    doctorId: 1,
    symptoms: "Mild exertional fatigue, intermittent evening headaches, and post-prandial lethargy over the past 6 weeks.",
    clinicalObservations: "BP 138/88 mmHg, Pulse 76 bpm regular, BMI 26.4 kg/m², S1/S2 normal, Chest clear, no peripheral edema.",
    assessmentDiagnosis: "Borderline Hypertension (Stage 1), Impaired Fasting Glucose / Pre-diabetes risk, Dyslipidemia suspect.",
    treatmentPlan: "1. Order Comprehensive Metabolic Panel, Lipid Profile, and HbA1c.\n2. Dietary sodium reduction (<2g/day) and structured 30-minute daily aerobic walking.\n3. Prescribe Metformin 500mg once daily after dinner.\n4. Re-evaluate in 2 weeks with report results.",
    followUpDate: "2026-08-28",
    followUpNotes: "Review blood investigation parameters and assess glycemic response.",
    notes: "Patient counseled on cardiometabolic prevention. Family history of early coronary artery disease noted in father.",
  },
];

export const seedPrescriptions = [
  {
    id: 1,
    consultationId: 1,
    patientId: 1,
    doctorId: 1,
    status: "ACTIVE",
    generalInstructions: "Take with meals. Maintain adequate hydration. Do not skip doses.",
  },
];

export const seedPrescriptionItems = [
  {
    id: 1,
    prescriptionId: 1,
    medicineName: "Metformin Hydrochloride 500mg SR",
    dosage: "500mg",
    frequency: "Once daily with dinner",
    duration: "30 days",
    instructions: "Take immediately following dinner with water to minimize GI upset.",
  },
  {
    id: 2,
    prescriptionId: 1,
    medicineName: "Telmisartan 40mg",
    dosage: "40mg",
    frequency: "Once daily in morning",
    duration: "30 days",
    instructions: "Take every morning after breakfast. Monitor home blood pressure weekly.",
  },
  {
    id: 3,
    prescriptionId: 1,
    medicineName: "Atorvastatin 10mg",
    dosage: "10mg",
    frequency: "Once daily at bedtime",
    duration: "30 days",
    instructions: "Take nightly before sleep.",
  },
];

export const seedInvestigations = [
  {
    id: 1,
    consultationId: 1,
    patientId: 1,
    doctorId: 1,
    testName: "Cardiometabolic & Lipid Panel (HbA1c, Fasting Glucose, Lipid Profile, Serum Creatinine)",
    category: "BLOOD",
    reason: "Assess glycemic control, atherogenic lipid fractions, and baseline renal function.",
    priority: "ROUTINE",
    instructions: "10-12 hours overnight fasting required. Water is permitted.",
    status: "COMPLETED",
    assignedLabId: 1,
  },
];

export const seedLabReports = [
  {
    id: 1,
    investigationId: 1,
    patientId: 1,
    labId: 1,
    testName: "Cardiometabolic & Lipid Profile Panel",
    category: "LAB_REPORT",
    summary: "Glycated Hemoglobin (HbA1c) indicates pre-diabetes range (6.6%). Elevated non-HDL and LDL cholesterol with normal kidney function markers.",
    structuredResults: [
      { parameter: "HbA1c (Glycated Hemoglobin)", value: "6.6", unit: "%", referenceRange: "4.0 - 5.6", flag: "HIGH" },
      { parameter: "Estimated Average Glucose (eAG)", value: "143", unit: "mg/dL", referenceRange: "70 - 114", flag: "HIGH" },
      { parameter: "Fasting Blood Glucose", value: "114", unit: "mg/dL", referenceRange: "70 - 99", flag: "HIGH" },
      { parameter: "Total Cholesterol", value: "218", unit: "mg/dL", referenceRange: "< 200", flag: "HIGH" },
      { parameter: "LDL Cholesterol (Direct)", value: "138", unit: "mg/dL", referenceRange: "< 100", flag: "HIGH" },
      { parameter: "HDL Cholesterol", value: "44", unit: "mg/dL", referenceRange: "> 40", flag: "NORMAL" },
      { parameter: "Triglycerides", value: "182", unit: "mg/dL", referenceRange: "< 150", flag: "HIGH" },
      { parameter: "Serum Creatinine", value: "0.92", unit: "mg/dL", referenceRange: "0.70 - 1.20", flag: "NORMAL" },
      { parameter: "eGFR (CKD-EPI)", value: "98", unit: "mL/min/1.73m²", referenceRange: "> 90", flag: "NORMAL" },
    ],
    referenceRanges: "Biological Reference Intervals per NABL & IFCC Guidelines 2026",
    fileUrl: "/reports/ABC-LAB-2026-CS2048.pdf",
    status: "PUBLISHED",
    verifiedByTechnicianId: 5,
    verifiedAt: new Date("2026-08-21T11:30:00Z"),
  },
];

export const seedAccessRequests = [
  {
    id: 1,
    patientId: 1,
    requesterDoctorId: 2, // Dr. Ananya Sharma (Cardiologist)
    purpose: "Pre-consultation review of cardiometabolic lab profile, lipid parameters, and current prescription history ahead of the scheduled cardiology assessment.",
    dataScopes: ["CONSULTATIONS", "PRESCRIPTIONS", "LAB_REPORTS", "JOURNEY", "VITALS"],
    status: "PENDING",
    otpCode: "749201",
    otpExpiresAt: new Date("2026-09-03T18:00:00Z"),
    requestedAt: new Date("2026-08-30T09:42:00Z"),
    respondedAt: null,
  },
  {
    id: 2,
    patientId: 1,
    requesterDoctorId: 1, // Dr. Rahul Mehta
    purpose: "Primary care continuum, consultation notes recording, and longitudinal treatment monitoring.",
    dataScopes: ["CONSULTATIONS", "PRESCRIPTIONS", "LAB_REPORTS", "JOURNEY", "VITALS", "ORDERS"],
    status: "ALLOWED",
    otpCode: "204819",
    otpExpiresAt: new Date("2026-08-15T00:00:00Z"),
    requestedAt: new Date("2026-08-12T10:05:00Z"),
    respondedAt: new Date("2026-08-12T10:07:00Z"),
  },
];

export const seedConsentRecords = [
  {
    id: 1,
    patientId: 1,
    doctorId: 1, // Dr. Rahul Mehta
    grantedScopes: ["CONSULTATIONS", "PRESCRIPTIONS", "LAB_REPORTS", "JOURNEY", "VITALS", "ORDERS"],
    status: "ACTIVE",
    grantedAt: new Date("2026-08-12T10:07:00Z"),
    expiresAt: new Date("2027-08-12T10:07:00Z"),
    revokedAt: null,
  },
];

export const seedPharmacyOrders = [
  {
    id: 1,
    orderNumber: "PS-2048",
    patientId: 1,
    pharmacyId: 2, // XYZ Pharmacy
    prescriptionId: 1,
    status: "PREPARING",
    subtotal: "760.00",
    tax: "90.00",
    totalAmount: "850.00",
    deliveryAddress: "Flat 402, Palm Meadows, Indiranagar, Bengaluru, Karnataka 560038",
    timeline: [
      { stage: "ORDER_PLACED", label: "Order Placed", time: "12 Aug 2026, 12:30 PM", completed: true },
      { stage: "PRESCRIPTION_VERIFIED", label: "Prescription Verified by Pharmacist", time: "12 Aug 2026, 12:45 PM", completed: true },
      { stage: "QUOTE_ISSUED", label: "Bill Generated & Paid (₹850)", time: "12 Aug 2026, 01:10 PM", completed: true },
      { stage: "PREPARING", label: "Medicines Packed & Checked", time: "12 Aug 2026, 02:00 PM", completed: true },
      { stage: "DISPATCHED", label: "Out for Delivery", time: "Estimated Today, 05:00 PM", completed: false },
      { stage: "DELIVERED", label: "Delivered", time: "Pending Delivery", completed: false },
    ],
  },
  {
    id: 2,
    orderNumber: "PS-1972",
    patientId: 1,
    pharmacyId: 2,
    prescriptionId: null,
    status: "DELIVERED",
    subtotal: "370.00",
    tax: "40.00",
    totalAmount: "410.00",
    deliveryAddress: "Flat 402, Palm Meadows, Indiranagar, Bengaluru, Karnataka 560038",
    timeline: [
      { stage: "ORDER_PLACED", label: "Order Placed", time: "02 Aug 2026, 09:15 AM", completed: true },
      { stage: "DELIVERED", label: "Delivered to Rahul Sharma", time: "02 Aug 2026, 02:30 PM", completed: true },
    ],
  },
];

export const seedPharmacyOrderItems = [
  {
    id: 1,
    orderId: 1,
    medicineName: "Metformin Hydrochloride 500mg SR (Strip of 15 x 2)",
    quantity: 2,
    unitPrice: "85.00",
    totalPrice: "170.00",
    inStock: true,
  },
  {
    id: 2,
    orderId: 1,
    medicineName: "Telmisartan 40mg (Strip of 15 x 2)",
    quantity: 2,
    unitPrice: "145.00",
    totalPrice: "290.00",
    inStock: true,
  },
  {
    id: 3,
    orderId: 1,
    medicineName: "Atorvastatin 10mg (Strip of 15 x 2)",
    quantity: 2,
    unitPrice: "150.00",
    totalPrice: "300.00",
    inStock: true,
  },
];

export const seedPayments = [
  {
    id: 1,
    patientId: 1,
    orderId: null,
    appointmentId: 1,
    investigationId: null,
    paymentType: "APPOINTMENT",
    amount: "850.00",
    currency: "INR",
    status: "PAID",
    paymentMethod: "DEMO_SANDBOX",
    transactionRef: "CS-PAY-TXN-9481028",
    paidAt: new Date("2026-08-11T16:20:00Z"),
  },
  {
    id: 2,
    patientId: 1,
    orderId: 1,
    appointmentId: null,
    investigationId: null,
    paymentType: "PHARMACY",
    amount: "850.00",
    currency: "INR",
    status: "PAID",
    paymentMethod: "DEMO_SANDBOX",
    transactionRef: "CS-PAY-TXN-9482711",
    paidAt: new Date("2026-08-12T13:10:00Z"),
  },
];

export const seedInvoices = [
  {
    id: 1,
    paymentId: 1,
    invoiceNumber: "INV-2048-01",
    patientId: 1,
    billingName: "Rahul Sharma",
    billingAddress: "Flat 402, Palm Meadows, Indiranagar, Bengaluru, Karnataka 560038",
    lineItems: [
      { description: "Initial Clinical Consultation (Dr. Rahul Mehta)", quantity: 1, amount: 850 }
    ],
    subtotal: "850.00",
    tax: "0.00",
    totalAmount: "850.00",
    issueDate: "2026-08-11",
  },
  {
    id: 2,
    paymentId: 2,
    invoiceNumber: "INV-2048-02",
    patientId: 1,
    billingName: "Rahul Sharma",
    billingAddress: "Flat 402, Palm Meadows, Indiranagar, Bengaluru, Karnataka 560038",
    lineItems: [
      { description: "Prescription Medicines (Order #PS-2048)", quantity: 3, amount: 760 },
      { description: "GST & Handling", quantity: 1, amount: 90 }
    ],
    subtotal: "760.00",
    tax: "90.00",
    totalAmount: "850.00",
    issueDate: "2026-08-12",
  },
];

export const seedHealthcareJourneyEvents = [
  {
    id: 1,
    patientId: 1,
    eventType: "SPECIALIST_CONSULTATION",
    sourceEntity: "appointment",
    sourceEntityId: 3,
    title: "Specialist Cardiology Consultation",
    provider: "Dr. Ananya Sharma",
    organization: "Aster Grove Heart Clinic",
    date: "02 Sep 2026",
    status: "UPCOMING",
    description: "Referred by Dr. Rahul Mehta for cardiovascular risk stratification and lipid optimization.",
    accent: "violet",
    metadata: { appointmentId: 3, doctorId: 2, mode: "In-clinic visit" },
  },
  {
    id: 2,
    patientId: 1,
    eventType: "FOLLOW_UP",
    sourceEntity: "appointment",
    sourceEntityId: 2,
    title: "Follow-up Consultation",
    provider: "Dr. Rahul Mehta",
    organization: "Northstar Medical Centre",
    date: "28 Aug 2026",
    status: "UPCOMING",
    description: "Review glycemic markers, blood pressure records, and discuss specialist referral.",
    accent: "mint",
    metadata: { appointmentId: 2, doctorId: 1, mode: "Video consultation" },
  },
  {
    id: 3,
    patientId: 1,
    eventType: "REPORT",
    sourceEntity: "lab_report",
    sourceEntityId: 1,
    title: "Cardiometabolic & Lipid Panel Report Ready",
    provider: "ABC Diagnostics",
    organization: "Richmond Road branch",
    date: "21 Aug 2026",
    status: "COMPLETED",
    description: "NABL verified report received. HbA1c 6.6%, Fasting Glucose 114 mg/dL, LDL 138 mg/dL.",
    accent: "blue",
    metadata: { reportId: 1, labId: 1 },
  },
  {
    id: 4,
    patientId: 1,
    eventType: "LAB_TEST",
    sourceEntity: "investigation",
    sourceEntityId: 1,
    title: "Diagnostic Blood Sample Collected",
    provider: "ABC Diagnostics",
    organization: "Richmond Road branch",
    date: "19 Aug 2026",
    status: "COMPLETED",
    description: "Sample collected for Fasting Blood Glucose, HbA1c, Serum Creatinine, and Lipid Profile.",
    accent: "violet",
    metadata: { investigationId: 1 },
  },
  {
    id: 5,
    patientId: 1,
    eventType: "PHARMACY_ORDER",
    sourceEntity: "pharmacy_order",
    sourceEntityId: 1,
    title: "Prescription Filled & Dispensed",
    provider: "XYZ Pharmacy",
    organization: "XYZ Pharmacy · Order #PS-2048",
    date: "12 Aug 2026",
    status: "IN_PROGRESS",
    description: "Metformin 500mg SR, Telmisartan 40mg, and Atorvastatin 10mg prepared for delivery.",
    accent: "amber",
    metadata: { orderId: 1, pharmacyId: 2 },
  },
  {
    id: 6,
    patientId: 1,
    eventType: "TREATMENT",
    sourceEntity: "prescription",
    sourceEntityId: 1,
    title: "Cardiometabolic Regimen Initiated",
    provider: "Dr. Rahul Mehta",
    organization: "Northstar Medical Centre",
    date: "12 Aug 2026",
    status: "COMPLETED",
    description: "Prescribed Metformin 500mg, Telmisartan 40mg, and Atorvastatin 10mg following initial consultation.",
    accent: "amber",
    metadata: { prescriptionId: 1 },
  },
  {
    id: 7,
    patientId: 1,
    eventType: "CONSULTATION",
    sourceEntity: "consultation",
    sourceEntityId: 1,
    title: "Initial Medical Consultation",
    provider: "Dr. Rahul Mehta",
    organization: "Northstar Medical Centre",
    date: "12 Aug 2026",
    status: "COMPLETED",
    description: "Symptoms reviewed. BP recorded at 138/88 mmHg. Comprehensive blood investigations ordered.",
    accent: "rose",
    metadata: { consultationId: 1, appointmentId: 1 },
  },
  {
    id: 8,
    patientId: 1,
    eventType: "SYMPTOMS",
    sourceEntity: "manual",
    sourceEntityId: null,
    title: "Symptoms Logged",
    provider: "Rahul Sharma (Self-Reported)",
    organization: "CareSync Patient Journal",
    date: "08 Aug 2026",
    status: "COMPLETED",
    description: "Reported intermittent fatigue, mild afternoon dizziness, and elevated thirst.",
    accent: "teal",
    metadata: {},
  },
];

export const seedPatientVitals = [
  {
    id: 1,
    patientId: 1,
    recordedAt: "2026-08-08",
    systolicBp: 142,
    diastolicBp: 90,
    bloodGlucose: 122,
    fasting: true,
    heartRate: 78,
    weightKg: "76.50",
    hba1c: null,
    notes: "Home BP monitor reading - morning fasting.",
  },
  {
    id: 2,
    patientId: 1,
    recordedAt: "2026-08-12",
    systolicBp: 138,
    diastolicBp: 88,
    bloodGlucose: 118,
    fasting: true,
    heartRate: 76,
    weightKg: "76.20",
    hba1c: null,
    notes: "Recorded during clinical consultation at Northstar Medical.",
  },
  {
    id: 3,
    patientId: 1,
    recordedAt: "2026-08-19",
    systolicBp: 132,
    diastolicBp: 84,
    bloodGlucose: 114,
    fasting: true,
    heartRate: 74,
    weightKg: "75.80",
    hba1c: "6.60",
    notes: "Lab confirmed fasting glucose and HbA1c at ABC Diagnostics.",
  },
  {
    id: 4,
    patientId: 1,
    recordedAt: "2026-08-27",
    systolicBp: 126,
    diastolicBp: 80,
    bloodGlucose: 104,
    fasting: true,
    heartRate: 72,
    weightKg: "75.10",
    hba1c: null,
    notes: "Follow-up home reading after 2 weeks of medication and dietary salt reduction.",
  },
];

export const seedNotifications = [
  {
    id: 1,
    userId: 1,
    title: "Access Request from Dr. Ananya Sharma",
    message: "Dr. Ananya Sharma has requested access to your cardiometabolic reports and history before your cardiology consultation.",
    type: "ACCESS_REQUEST",
    link: "/app/consent",
    isRead: false,
  },
  {
    id: 2,
    userId: 1,
    title: "Diagnostic Lab Report Published",
    message: "ABC Diagnostics has verified and published your Cardiometabolic & Lipid Profile report.",
    type: "REPORT_READY",
    link: "/app/journey",
    isRead: false,
  },
  {
    id: 3,
    userId: 1,
    title: "Upcoming Video Consultation",
    message: "You have a follow-up video consultation with Dr. Rahul Mehta on 28 Aug 2026 at 04:30 PM.",
    type: "APPOINTMENT_UPDATE",
    link: "/app",
    isRead: false,
  },
  {
    id: 4,
    userId: 1,
    title: "Pharmacy Order Out for Delivery",
    message: "XYZ Pharmacy Order #PS-2048 is being prepared for scheduled doorstep delivery.",
    type: "PHARMACY_UPDATE",
    link: "/app/orders",
    isRead: true,
  },
];

export const seedAuditLogs = [
  {
    id: 1,
    actorId: 2,
    actorRole: "DOCTOR",
    action: "PATIENT_RECORD_VIEW",
    entityType: "PATIENT",
    entityId: 1,
    patientId: 1,
    organizationId: null,
    ipAddress: "192.168.1.45",
    result: "SUCCESS",
    metadata: { reason: "Consultation preparation", grantedScopes: ["CONSULTATIONS", "PRESCRIPTIONS", "LAB_REPORTS"] },
    timestamp: new Date("2026-08-12T09:58:00Z"),
  },
  {
    id: 2,
    actorId: 1,
    actorRole: "PATIENT",
    action: "CONSENT_GRANTED",
    entityType: "CONSENT_RECORD",
    entityId: 1,
    patientId: 1,
    organizationId: null,
    ipAddress: "103.21.14.88",
    result: "SUCCESS",
    metadata: { doctorId: 1, scopes: ["CONSULTATIONS", "PRESCRIPTIONS", "LAB_REPORTS", "JOURNEY", "VITALS", "ORDERS"] },
    timestamp: new Date("2026-08-12T10:07:00Z"),
  },
  {
    id: 3,
    actorId: 5,
    actorRole: "LAB_STAFF",
    action: "LAB_REPORT_PUBLISHED",
    entityType: "LAB_REPORT",
    entityId: 1,
    patientId: 1,
    organizationId: 1,
    ipAddress: "192.168.10.12",
    result: "SUCCESS",
    metadata: { labId: 1, testName: "Cardiometabolic & Lipid Profile Panel" },
    timestamp: new Date("2026-08-21T11:30:00Z"),
  },
];
